### ISSUE TITLE
Grouping into one Backend Folder

### ISSUE THREAD

**Issue by aayusharora** [JSS-OSDC/ROTI-BANK#1]
@shlok007 ,Maintain one single folder name Backend inside the directory ROTI-BANK,keep all your folders inside that.
Cheers:)

**Comment by shlok007** [comment]
Sir, can't we use separate branches for frontend and backend?

**Comment by aayusharora** [comment]
@shlok007 ,I don't think so ,Finally we will have to merge ,maintaining a seperate folder will do the stuff ,not confirmed actually.According to me directory structure can be ROTI_BANK/
                                                                                                                  /FRONTEND
                                                                                                                   /BACKEND
What say @spyshiv ,@DESHRAJ

**Comment by spyshiv** [comment]
The best approach will be something like this
Make a branch for backend 
Make another branch for frontend
And keep merging your code with master branch

**Comment by aayusharora** [comment]
@spyshiv Thanks ,It would be beneficial if  you can explain the following points :After studying ,I found out 
1. Branching for Frontend and Backend will have no effect.
   Reason: Suppose both Frontend and Backend developer are working in seperate folders on same branch, they will never run into conflict ,why we need branching then?
   1. The folder concept is best according to me ,the other way could be the two seperate repositories for both frontend and backend, which according to me depend on how we are going to deploy the project.
      @DESHRAJ any views?

**Comment by spyshiv** [comment]
@aayusharora  It depends upon the understanding between developers. And merge conflict occurs only when the same file is edited by two developers. You can view and remove the conflict easily.  BTW don't fear with conflicts. :laughing:

**Comment by aayusharora** [comment]
Thanks @spyshiv , :)
@shlok007 ,Can you take all your work in a single folder name Backend ?

**Comment by shlok007** [comment]
Ofcourse sir, your call! :+1:

**Comment by aayusharora** [comment]
Closing it :)
